inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
