inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 130
  IgnoredPatterns: ['(\A|\s)#']

Style/Documentation:
  Enabled: false
