name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: ruby:2.6.4
    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: bundle install --without development production --jobs 4 --retry 3
      - name: rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    container: ruby:2.6.4
    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: bundle install --without development production --jobs 4 --retry 3
      - name: rubocop
        run: bundle exec rubocop
  haml-lint:
    runs-on: ubuntu-latest
    container: ruby:2.6.4
    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: bundle install --without development production --jobs 4 --retry 3
      - name: haml-lint
        run: bundle exec haml-lint
