name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - name: node dependencies
        run: bin/yarn install
      - name: rails dependencies
        run: bundle install --without development production --jobs 4 --retry 3
      - name: rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag ~type:system
  rspec-system:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - name: node dependencies
        run: bin/yarn install
      - name: rails dependencies
        run: bundle install --without development production --jobs 4 --retry 3
      - name: rspec system
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag type:system
  rubocop:
    runs-on: ubuntu-latest
    container: ruby:2.6.5
    steps:
      - uses: actions/checkout@v1
      - name: install rubocop
        run: |
          gem install rubocop -v '0.74.0'
          gem install rubocop-performance -v '1.4.1'
          gem install rubocop-rails -v '2.3.2'
          gem install rubocop-rspec -v '1.35.0'
      - name: rubocop
        run: rubocop
  haml-lint:
    runs-on: ubuntu-latest
    container: ruby:2.6.5
    steps:
      - uses: actions/checkout@v1
      - name: install haml-lint
        run: gem install haml_lint -v '0.33.0'
      - name: haml-lint
        run: haml-lint
