name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag ~type:system
  rspec-system:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: Install bundler dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: Run rspec system specs
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag type:system
  license_finder:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        name: Cache bundler dependencies
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: Install bundler dependencies
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Run license_finder
        run: bundle exec license_finder
  rubocop:
    runs-on: ubuntu-latest
    container: ruby:2.7.0
    steps:
      - uses: actions/checkout@v1
      - name: Install rubocop
        run: |
          gem install rubocop -v '0.74.0'
          gem install rubocop-performance -v '1.4.1'
          gem install rubocop-rails -v '2.3.2'
          gem install rubocop-rspec -v '1.35.0'
      - name: Run rubocop
        run: rubocop
  haml-lint:
    runs-on: ubuntu-latest
    container: ruby:2.7.0
    steps:
      - uses: actions/checkout@v1
      - name: Install haml-lint
        run: gem install haml_lint -v '0.33.0'
      - name: Run haml-lint
        run: haml-lint
  stylelint:
    runs-on: ubuntu-latest
    container: node:13.1.0-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Install stylelint
        run: npm install --global stylelint stylelint-config-standard@19.0.0
      - name: Run stylelint
        run: stylelint '**/*.scss'
  standard:
    runs-on: ubuntu-latest
    container: node:13.1.0-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Install standard
        run: npm install --global standard@14.3.1
      - name: Run standard
        run: standard
  docs_lint:
    runs-on: ubuntu-latest
    container: python:slim
    steps:
      - uses: actions/checkout@v1
      - name: Install proselint
        run: pip install proselint
      - name: Run proselint
        run: proselint docs/
  markdown_lint:
    runs-on: ubuntu-latest
    container: ruby:2.7.0
    steps:
      - uses: actions/checkout@v1
      - name: Install mdl
        run: |
          gem install mdl
      - name: Run mdl
        run: mdl .
