name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: dependencies
        run: |
          sudo apt update && sudo apt install --assume-yes libsqlite3-dev
          gem install bundler -v 1.17.3
          bundle install --without production --jobs 4 --retry 3
      - name: rspec
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: dependencies
        run: |
          sudo apt update && sudo apt install --assume-yes libsqlite3-dev
          gem install bundler -v 1.17.3
          bundle install --without production --jobs 4 --retry 3
      - name: rubocop
        run: bundle exec rubocop
