name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: rails dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: rspec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag ~type:system
  rspec-system:
    runs-on: ubuntu-latest
    container: matteeyah/respondo-ci:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: node dependencies
        run: bin/yarn install --cache-folder vendor/yarn
      - name: rails dependencies
        run: bundle install --without development production --jobs 4 --retry 3 --path vendor/bundle
      - name: rspec system
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec --tag type:system
  rubocop:
    runs-on: ubuntu-latest
    container: ruby:2.6.5
    steps:
      - uses: actions/checkout@v1
      - name: install rubocop
        run: |
          gem install rubocop -v '0.74.0'
          gem install rubocop-performance -v '1.4.1'
          gem install rubocop-rails -v '2.3.2'
          gem install rubocop-rspec -v '1.35.0'
      - name: rubocop
        run: rubocop
  haml-lint:
    runs-on: ubuntu-latest
    container: ruby:2.6.5
    steps:
      - uses: actions/checkout@v1
      - name: install haml-lint
        run: gem install haml_lint -v '0.33.0'
      - name: haml-lint
        run: haml-lint
